CREATE TABLE guest (
    id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(30),
    phone VARCHAR(20),
    address VARCHAR(50)
 );

CREATE TABLE room (
    id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    number INTEGER,
    capacity INTEGER,
    service BOOLEAN,
    price DECIMAL(10, 3)
);

CREATE TABLE rent (
    id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    startDate DATE,
    endDate DATE,
    guestID BIGINT FOREIGN KEY REFERENCES guest,
    roomID BIGINT FOREIGN KEY REFERENCES room
);